### ISSUE TITLE
MaterialIcons error trying to use theme

### ISSUE THREAD

**Issue by rad-pat** [ITISFoundation/qx-osparc-theme#41]
Hi there, I've tried to use the theme locally but am experiencing some issue with the MaterialIcons, I receive errors such as `Assertion error! Virtual image source contains unkown font descriptor: Expected value to be typeof object but found MaterialIcons!` when I try to view a TreeVirtual. 

It looks like its trying to use an icon of `@MaterialIcons/reorder/15`

Similar errors can be seen in the console at https://itisfoundation.github.io/qx-osparc-theme/ when viewing the "Basic" tab, but for FontAwesomeSSolid `Assertion error! Virtual image source contains unkown font descriptor: Expected value to be typeof object but found FontAwesome5Solid!`

Viewing the TreeVirtual in the online demo gives 404 for items related to MaterialIcons, I guess this might be related. Please let me know if you need more information. 
Thanks,
Pat

**Comment by oetiker** [comment]
yep, the virtual tree thing is a bit of a throwback ... I have started work on integrating a version of this theme into proper qooxdoo, I will be looking into this problem there more closely. Nothing to demonstrate yet. sorry.

**Comment by rad-pat** [comment]
Thanks @oetiker, I'll look out for an update in the Gitter room 👍
